# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 03:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='completed',
            field=models.DateField(default=datetime.datetime(2017, 9, 18, 3, 43, 28, 274794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 9, 18, 3, 43, 28, 274860, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 9, 18, 3, 43, 28, 273966, tzinfo=utc)),
        ),
    ]
