# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170816_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
