# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170920_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='skills',
            new_name='services',
        ),
    ]
