# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170816_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default=1, upload_to='imagen'),
            preserve_default=False,
        ),
    ]
