# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171006_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
