# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_portfolio_client_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoportfolio',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='photoportfolio',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
