# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 15:23
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170816_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='blog/fotos')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 17, 15, 23, 43, 914311, tzinfo=utc)),
        ),
    ]
