# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170817_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='autor',
            field=models.ManyToManyField(to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 15, 56, 0, 367065, tzinfo=utc)),
        ),
    ]
