# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170818_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='slug',
            field=models.SlugField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(upload_to='', verbose_name='blog/fotos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 17, 48, 21, 360429, tzinfo=utc)),
        ),
    ]
