# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20170818_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(default=1, upload_to='blog/fotos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 18, 58, 32, 303336, tzinfo=utc)),
        ),
    ]
