# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20170818_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 20, 5, 28, 177893, tzinfo=utc)),
        ),
    ]
