# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_auto_20170818_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to='blog/fotos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 19, 2, 14, 59, 402241, tzinfo=utc)),
        ),
    ]
