# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_auto_20170821_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='foto',
            old_name='imagen',
            new_name='foto',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 15, 50, 17, 990093, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='foto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.CategoryFoto'),
        ),
    ]
