# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0073_auto_20170821_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryfoto',
            old_name='name',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 16, 7, 10, 224601, tzinfo=utc)),
        ),
    ]
