# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_auto_20170821_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryfoto',
            name='post',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='category',
        ),
        migrations.AddField(
            model_name='foto',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 16, 13, 59, 63412, tzinfo=utc)),
        ),
    ]
