# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_auto_20170821_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryFoto',
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 16, 38, 39, 444295, tzinfo=utc)),
        ),
    ]
