# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 20:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0097_auto_20170821_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='Post',
        ),
        migrations.AddField(
            model_name='post',
            name='fotos',
            field=models.ManyToManyField(to='blog.Foto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 20, 19, 3, 192151, tzinfo=utc)),
        ),
    ]
