# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0102_auto_20170821_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='foto',
            field=models.ImageField(default=1, upload_to='blog/fotos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 20, 54, 37, 955638, tzinfo=utc)),
        ),
    ]
