# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0113_auto_20170821_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 21, 32, 6, 47496, tzinfo=utc)),
        ),
    ]
