# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 22:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0122_auto_20170821_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fotos',
        ),
        migrations.AddField(
            model_name='foto',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=True, upload_to='blog/fotos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 22, 37, 0, 907686, tzinfo=utc)),
        ),
    ]
