# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0138_auto_20170822_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 23, 2, 53, 44, 486086, tzinfo=utc)),
        ),
    ]
