# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0142_auto_20170824_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default=1, upload_to='blog/fotos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 24, 19, 2, 46, 245412, tzinfo=utc)),
        ),
    ]
