# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0151_auto_20170825_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 25, 23, 26, 12, 384801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 25, 23, 26, 12, 383226, tzinfo=utc)),
        ),
    ]
