# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0152_auto_20170825_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='autor',
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 25, 23, 36, 4, 787410, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Portafolio',
        ),
    ]
