# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0154_auto_20170825_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='Post',
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 25, 23, 45, 15, 84157, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 25, 23, 45, 15, 82416, tzinfo=utc)),
        ),
    ]
