# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 02:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0160_auto_20170825_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='portafolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Portafolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 2, 15, 53, 953994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 2, 15, 53, 953047, tzinfo=utc)),
        ),
    ]
