# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0172_auto_20170826_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='client',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portafolio',
            name='completed',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 5, 20, 44, 907160, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='create',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portafolio',
            name='skills',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 5, 20, 44, 907245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 5, 20, 44, 906184, tzinfo=utc)),
        ),
    ]
