# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 22:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0174_auto_20170826_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='completed',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 22, 52, 15, 527778, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 22, 52, 15, 527858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 22, 52, 15, 526769, tzinfo=utc)),
        ),
    ]
