# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 05:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0176_auto_20170826_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='completed',
            field=models.DateField(default=datetime.datetime(2017, 9, 9, 5, 22, 49, 389593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 9, 9, 5, 22, 49, 389678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 9, 9, 5, 22, 49, 388486, tzinfo=utc)),
        ),
    ]
