# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 23:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170817_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='caption',
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 17, 23, 40, 25, 426646, tzinfo=utc)),
        ),
    ]
