# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20170818_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='id',
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 19, 39, 17, 788251, tzinfo=utc)),
        ),
    ]
