# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20170818_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 21, 20, 41, 853196, tzinfo=utc)),
        ),
    ]
