# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_auto_20170818_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='Post',
        ),
        migrations.AddField(
            model_name='foto',
            name='imagen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 21, 30, 2, 95369, tzinfo=utc)),
        ),
    ]
