# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20170818_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 22, 57, 54, 979931, tzinfo=utc)),
        ),
    ]
