# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_auto_20170818_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 13, 48, 59, 79314, tzinfo=utc)),
        ),
    ]
