# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0068_auto_20170821_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='imagen',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 14, 42, 31, 386299, tzinfo=utc)),
        ),
    ]
