# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0074_auto_20170821_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfoto',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 16, 10, 23, 113881, tzinfo=utc)),
        ),
    ]
