# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_auto_20170821_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='foto',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 17, 9, 42, 140427, tzinfo=utc)),
        ),
    ]
