# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0081_auto_20170821_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='post',
        ),
        migrations.AddField(
            model_name='foto',
            name='post',
            field=models.ManyToManyField(to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 17, 23, 16, 955019, tzinfo=utc)),
        ),
    ]
