# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0086_auto_20170821_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AddField(
            model_name='post',
            name='fotos',
            field=models.ManyToManyField(to='blog.Foto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 19, 17, 10, 23468, tzinfo=utc)),
        ),
    ]
