# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0117_auto_20170821_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fotos',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=True, upload_to='blog/fotos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 21, 52, 2, 562975, tzinfo=utc)),
        ),
    ]
