# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 01:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0133_auto_20170821_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 22, 1, 23, 22, 532959, tzinfo=utc)),
        ),
    ]
