# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0135_auto_20170822_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 22, 17, 7, 33, 946107, tzinfo=utc)),
        ),
    ]
