# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0139_auto_20170822_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 23, 19, 21, 52, 125299, tzinfo=utc)),
        ),
    ]
