# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:42
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0153_auto_20170825_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('imagen', models.ImageField(blank=True, upload_to='blog/fotos/')),
                ('video', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('presentar', models.BooleanField(default=True)),
                ('publicado', models.DateField(default=datetime.datetime(2017, 8, 25, 23, 42, 59, 197665, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 25, 23, 42, 59, 196067, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='Post',
            field=models.ManyToManyField(to='blog.Post'),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
    ]
