# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0163_auto_20170825_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Photos',
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 2, 53, 43, 185745, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 2, 53, 43, 184739, tzinfo=utc)),
        ),
    ]
